name: dart_web3
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 0.0.4
homepage: https://github.com/pay-2-bit-human/dart_web3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # code generation for contracts, shouldn't be imported outside of lib/src/builder/
  build: ^2.4.1
  build_config: ^1.1.1
  dart_style: ^2.0.0
  code_builder: ^4.5.0
  path: ^1.8.0

  built_collection: ^5.1.0
  pointycastle: ^3.9.1
  convert: ^3.1.1
  meta: ^1.1.0
  http: ^1.2.2
  js: ^0.6.3
  uuid: ^4.5.0
  typed_data: ^1.1.6
  stream_channel: ^2.1.1
  stream_transform: ^2.0.0
  json_rpc_2: ^3.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  async: ^2.8.2
  build_runner: ^2.4.12
  build_test: ^2.1.0
  web_socket_channel: ^3.0.1
  test: ^1.24.1
  coverage: ^1.9.2
